# Generated by Django 5.1.6 on 2025-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_locations',
            field=models.ManyToManyField(related_name='vehicles', to='staff.location'),
        ),
    ]
