# Generated by Django 5.1.6 on 2025-04-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0003_alter_user_role_agency_agent'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='regulator.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
