# Generated by Django 5.1.6 on 2025-06-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0011_remove_customer_lead'),
        ('staff', '0002_alter_booking_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='agent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='regulator.agent'),
            preserve_default=False,
        ),
    ]
