# Generated by Django 5.1.6 on 2025-06-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_vehicle_pickup_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
    ]
