# Generated by Django 5.1.6 on 2025-06-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0011_remove_customer_lead'),
        ('staff', '0003_vehicle_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(blank=True, max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='regulator.agency')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pickup_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.location'),
            preserve_default=False,
        ),
    ]
