# Generated by Django 5.1.6 on 2025-03-03 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_vehicle_maintenancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='available',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='maintenance_records',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entries', to='staff.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[('company', 'Company Owned'), ('private', 'Privately Owned')], max_length=10),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='staff.vehicle')),
            ],
        ),
    ]
