# Generated by Django 5.1.6 on 2025-07-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
        ('staff', '0005_booking_booking_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='rentals.bookingrequest'),
        ),
    ]
