# Generated by Django 5.1.6 on 2025-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_vehicle_available_vehicle_maintenance_records_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
