# Generated by Django 5.1.6 on 2025-07-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_booking_booking_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='pickup_locations',
        ),
    ]
