# Generated by Django 5.1.6 on 2025-07-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0002_agency_logo'),
        ('staff', '0007_remove_vehicle_pickup_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='regulator.agency'),
        ),
    ]
