# Generated by Django 5.1.6 on 2025-03-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_vehicle_price_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(choices=[('maintenance', 'Maintenance'), ('booking', 'Booking'), ('other', 'Other')], default='other', max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_periods', to='staff.vehicle')),
            ],
        ),
    ]
