# Generated by Django 5.1.6 on 2025-07-18 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0002_agency_logo'),
        ('staff', '0008_booking_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='agent',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='regulator.agency'),
            preserve_default=False,
        ),
    ]
