# Generated by Django 5.1.6 on 2025-03-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_vehicleunavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
    ]
