# Generated by Django 5.1.6 on 2025-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_vehicle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
