# Generated by Django 5.1.6 on 2025-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_vehicle_deposit_vehicle_manufacture_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('DR', 'Dr')], default='MR', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('national_id', models.CharField(max_length=11, unique=True)),
                ('drivers_license', models.ImageField(blank=True, null=True, upload_to='drivers_licenses/')),
                ('next_of_kin1_first_name', models.CharField(max_length=100)),
                ('next_of_kin1_last_name', models.CharField(max_length=100)),
                ('next_of_kin1_id_number', models.CharField(max_length=11)),
                ('next_of_kin1_phone', models.CharField(max_length=15)),
                ('next_of_kin2_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin2_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin2_id_number', models.CharField(blank=True, max_length=11, null=True)),
                ('next_of_kin2_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_booking_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
