# Generated by Django 5.1.6 on 2025-04-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_customer_address_line2_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mobile transfer', 'Mobile Transfer'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], default='cash', max_length=20)),
                ('booking_status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('active', 'Active'), ('canceled', 'Canceled')], default='upcoming', max_length=20)),
                ('estimated_mileage', models.PositiveIntegerField(default=0)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount_description', models.TextField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('dropoff_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='staff.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='staff.vehicle')),
            ],
        ),
    ]
