# Generated by Django 5.1.6 on 2025-04-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mobile transfer', 'Mobile Transfer'), ('debit card', 'Debit Card'), ('cash', 'Cash')], default='cash', max_length=20),
        ),
    ]
