# Generated by Django 5.1.6 on 2025-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0011_remove_customer_lead'),
        ('rentals', '0002_bookingrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='lead',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
