# Generated by Django 5.1.6 on 2025-05-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0011_remove_customer_lead'),
        ('rentals', '0003_remove_bookingrequest_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='regulator.customer'),
            preserve_default=False,
        ),
    ]
