# Generated by Django 5.1.6 on 2025-06-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0011_remove_customer_lead'),
        ('rentals', '0004_bookingrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who accepted this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='regulator.agent'),
        ),
    ]
