# Generated by Django 5.1.6 on 2025-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_bookingrequest_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='customer_docs_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='dummy_payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='is_confirmed_by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
