# Generated by Django 5.1.6 on 2025-06-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_bookingrequest_customer_docs_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='dropoff_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
