# Generated by Django 5.1.6 on 2025-06-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_bookingrequest_dropoff_location_and_more'),
        ('staff', '0004_location_vehicle_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='dropoff_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_requests', to='staff.location'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='pickup_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='staff.location'),
            preserve_default=False,
        ),
    ]
