# Generated by Django 5.1.6 on 2025-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency_logos/'),
        ),
    ]
