# Generated by Django 5.1.6 on 2025-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0003_alter_user_role_agency_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
