# Generated by Django 5.1.6 on 2025-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0005_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
