# Generated by Django 5.1.6 on 2025-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0006_alter_customer_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
