# Generated by Django 5.1.6 on 2025-05-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0007_alter_customer_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_public_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='related_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regulator.agency'),
        ),
        migrations.AddField(
            model_name='customer',
            name='related_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='regulator.agent'),
        ),
    ]
