# Generated by Django 5.1.6 on 2025-05-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0008_customer_is_public_only_customer_related_agency_and_more'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_customer', to='rentals.lead'),
        ),
    ]
