# Generated by Django 5.1.6 on 2025-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0009_customer_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='related_agent',
        ),
        migrations.AddField(
            model_name='customer',
            name='agents',
            field=models.ManyToManyField(blank=True, help_text='Agents linked to this customer', related_name='customers', to='regulator.agent'),
        ),
    ]
