# Generated by Django 5.1.6 on 2025-05-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulator', '0010_remove_customer_related_agent_customer_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lead',
        ),
    ]
